services:
    ciakval.vipposts.listener:
        class: ciakval\vipposts\event\listener
        arguments:
            - @auth
            - @user
            - @request
        tags:
            - { name: event.listener }
