services:
    ciakval.vipposts.listener:
        class: ciakval\vipposts\event\listener
        arguments:
            - @auth
            - @user
            - @request
            - @template
            - @config
            - @config_text
            - @dbal.conn
        tags:
            - { name: event.listener }
